// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
)

// NewConfigurationHandlerInterface creates a new instance of ConfigurationHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationHandlerInterface[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationHandlerInterface[T] {
	mock := &ConfigurationHandlerInterface[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigurationHandlerInterface is an autogenerated mock type for the ConfigurationHandlerInterface type
type ConfigurationHandlerInterface[T any] struct {
	mock.Mock
}

type ConfigurationHandlerInterface_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *ConfigurationHandlerInterface[T]) EXPECT() *ConfigurationHandlerInterface_Expecter[T] {
	return &ConfigurationHandlerInterface_Expecter[T]{mock: &_m.Mock}
}

// Load provides a mock function for the type ConfigurationHandlerInterface
func (_mock *ConfigurationHandlerInterface[T]) Load() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConfigurationHandlerInterface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type ConfigurationHandlerInterface_Load_Call[T any] struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *ConfigurationHandlerInterface_Expecter[T]) Load() *ConfigurationHandlerInterface_Load_Call[T] {
	return &ConfigurationHandlerInterface_Load_Call[T]{Call: _e.mock.On("Load")}
}

func (_c *ConfigurationHandlerInterface_Load_Call[T]) Run(run func()) *ConfigurationHandlerInterface_Load_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigurationHandlerInterface_Load_Call[T]) Return(b bool, err error) *ConfigurationHandlerInterface_Load_Call[T] {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ConfigurationHandlerInterface_Load_Call[T]) RunAndReturn(run func() (bool, error)) *ConfigurationHandlerInterface_Load_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Provide provides a mock function for the type ConfigurationHandlerInterface
func (_mock *ConfigurationHandlerInterface[T]) Provide() (*T, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*T, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConfigurationHandlerInterface_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type ConfigurationHandlerInterface_Provide_Call[T any] struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
func (_e *ConfigurationHandlerInterface_Expecter[T]) Provide() *ConfigurationHandlerInterface_Provide_Call[T] {
	return &ConfigurationHandlerInterface_Provide_Call[T]{Call: _e.mock.On("Provide")}
}

func (_c *ConfigurationHandlerInterface_Provide_Call[T]) Run(run func()) *ConfigurationHandlerInterface_Provide_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigurationHandlerInterface_Provide_Call[T]) Return(v *T, err error) *ConfigurationHandlerInterface_Provide_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *ConfigurationHandlerInterface_Provide_Call[T]) RunAndReturn(run func() (*T, error)) *ConfigurationHandlerInterface_Provide_Call[T] {
	_c.Call.Return(run)
	return _c
}
