// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"context"
	"io"
	"os"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewDaoFactoryInterface creates a new instance of DaoFactoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDaoFactoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DaoFactoryInterface {
	mock := &DaoFactoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DaoFactoryInterface is an autogenerated mock type for the DaoFactoryInterface type
type DaoFactoryInterface struct {
	mock.Mock
}

type DaoFactoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *DaoFactoryInterface) EXPECT() *DaoFactoryInterface_Expecter {
	return &DaoFactoryInterface_Expecter{mock: &_m.Mock}
}

// GetDataFromLocal provides a mock function for the type DaoFactoryInterface
func (_mock *DaoFactoryInterface) GetDataFromLocal(filePointer *os.File) ([]byte, error) {
	ret := _mock.Called(filePointer)

	if len(ret) == 0 {
		panic("no return value specified for GetDataFromLocal")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*os.File) ([]byte, error)); ok {
		return returnFunc(filePointer)
	}
	if returnFunc, ok := ret.Get(0).(func(*os.File) []byte); ok {
		r0 = returnFunc(filePointer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*os.File) error); ok {
		r1 = returnFunc(filePointer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DaoFactoryInterface_GetDataFromLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataFromLocal'
type DaoFactoryInterface_GetDataFromLocal_Call struct {
	*mock.Call
}

// GetDataFromLocal is a helper method to define mock.On call
//   - filePointer
func (_e *DaoFactoryInterface_Expecter) GetDataFromLocal(filePointer interface{}) *DaoFactoryInterface_GetDataFromLocal_Call {
	return &DaoFactoryInterface_GetDataFromLocal_Call{Call: _e.mock.On("GetDataFromLocal", filePointer)}
}

func (_c *DaoFactoryInterface_GetDataFromLocal_Call) Run(run func(filePointer *os.File)) *DaoFactoryInterface_GetDataFromLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*os.File))
	})
	return _c
}

func (_c *DaoFactoryInterface_GetDataFromLocal_Call) Return(bytes []byte, err error) *DaoFactoryInterface_GetDataFromLocal_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *DaoFactoryInterface_GetDataFromLocal_Call) RunAndReturn(run func(filePointer *os.File) ([]byte, error)) *DaoFactoryInterface_GetDataFromLocal_Call {
	_c.Call.Return(run)
	return _c
}

// GetS3Object provides a mock function for the type DaoFactoryInterface
func (_mock *DaoFactoryInterface) GetS3Object(ctx context.Context, bucket string, key string) (*s3.GetObjectOutput, error) {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for GetS3Object")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*s3.GetObjectOutput, error)); ok {
		return returnFunc(ctx, bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *s3.GetObjectOutput); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DaoFactoryInterface_GetS3Object_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetS3Object'
type DaoFactoryInterface_GetS3Object_Call struct {
	*mock.Call
}

// GetS3Object is a helper method to define mock.On call
//   - ctx
//   - bucket
//   - key
func (_e *DaoFactoryInterface_Expecter) GetS3Object(ctx interface{}, bucket interface{}, key interface{}) *DaoFactoryInterface_GetS3Object_Call {
	return &DaoFactoryInterface_GetS3Object_Call{Call: _e.mock.On("GetS3Object", ctx, bucket, key)}
}

func (_c *DaoFactoryInterface_GetS3Object_Call) Run(run func(ctx context.Context, bucket string, key string)) *DaoFactoryInterface_GetS3Object_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DaoFactoryInterface_GetS3Object_Call) Return(getObjectOutput *s3.GetObjectOutput, err error) *DaoFactoryInterface_GetS3Object_Call {
	_c.Call.Return(getObjectOutput, err)
	return _c
}

func (_c *DaoFactoryInterface_GetS3Object_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) (*s3.GetObjectOutput, error)) *DaoFactoryInterface_GetS3Object_Call {
	_c.Call.Return(run)
	return _c
}

// ReadContent provides a mock function for the type DaoFactoryInterface
func (_mock *DaoFactoryInterface) ReadContent(data io.ReadCloser) ([]byte, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ReadContent")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.ReadCloser) ([]byte, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(io.ReadCloser) []byte); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.ReadCloser) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DaoFactoryInterface_ReadContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadContent'
type DaoFactoryInterface_ReadContent_Call struct {
	*mock.Call
}

// ReadContent is a helper method to define mock.On call
//   - data
func (_e *DaoFactoryInterface_Expecter) ReadContent(data interface{}) *DaoFactoryInterface_ReadContent_Call {
	return &DaoFactoryInterface_ReadContent_Call{Call: _e.mock.On("ReadContent", data)}
}

func (_c *DaoFactoryInterface_ReadContent_Call) Run(run func(data io.ReadCloser)) *DaoFactoryInterface_ReadContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.ReadCloser))
	})
	return _c
}

func (_c *DaoFactoryInterface_ReadContent_Call) Return(bytes []byte, err error) *DaoFactoryInterface_ReadContent_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *DaoFactoryInterface_ReadContent_Call) RunAndReturn(run func(data io.ReadCloser) ([]byte, error)) *DaoFactoryInterface_ReadContent_Call {
	_c.Call.Return(run)
	return _c
}
