// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
	"golang.a2z.com/demanddriventrafficevaluator/interfaces"
)

// NewExperimentConfigurationHandlerInterface creates a new instance of ExperimentConfigurationHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExperimentConfigurationHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExperimentConfigurationHandlerInterface {
	mock := &ExperimentConfigurationHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExperimentConfigurationHandlerInterface is an autogenerated mock type for the ExperimentConfigurationHandlerInterface type
type ExperimentConfigurationHandlerInterface struct {
	mock.Mock
}

type ExperimentConfigurationHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ExperimentConfigurationHandlerInterface) EXPECT() *ExperimentConfigurationHandlerInterface_Expecter {
	return &ExperimentConfigurationHandlerInterface_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type ExperimentConfigurationHandlerInterface
func (_mock *ExperimentConfigurationHandlerInterface) Load() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExperimentConfigurationHandlerInterface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type ExperimentConfigurationHandlerInterface_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *ExperimentConfigurationHandlerInterface_Expecter) Load() *ExperimentConfigurationHandlerInterface_Load_Call {
	return &ExperimentConfigurationHandlerInterface_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *ExperimentConfigurationHandlerInterface_Load_Call) Run(run func()) *ExperimentConfigurationHandlerInterface_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExperimentConfigurationHandlerInterface_Load_Call) Return(b bool, err error) *ExperimentConfigurationHandlerInterface_Load_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ExperimentConfigurationHandlerInterface_Load_Call) RunAndReturn(run func() (bool, error)) *ExperimentConfigurationHandlerInterface_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Provide provides a mock function for the type ExperimentConfigurationHandlerInterface
func (_mock *ExperimentConfigurationHandlerInterface) Provide() (*interfaces.ExperimentConfiguration, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 *interfaces.ExperimentConfiguration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*interfaces.ExperimentConfiguration, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *interfaces.ExperimentConfiguration); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ExperimentConfiguration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExperimentConfigurationHandlerInterface_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type ExperimentConfigurationHandlerInterface_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
func (_e *ExperimentConfigurationHandlerInterface_Expecter) Provide() *ExperimentConfigurationHandlerInterface_Provide_Call {
	return &ExperimentConfigurationHandlerInterface_Provide_Call{Call: _e.mock.On("Provide")}
}

func (_c *ExperimentConfigurationHandlerInterface_Provide_Call) Run(run func()) *ExperimentConfigurationHandlerInterface_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExperimentConfigurationHandlerInterface_Provide_Call) Return(experimentConfiguration *interfaces.ExperimentConfiguration, err error) *ExperimentConfigurationHandlerInterface_Provide_Call {
	_c.Call.Return(experimentConfiguration, err)
	return _c
}

func (_c *ExperimentConfigurationHandlerInterface_Provide_Call) RunAndReturn(run func() (*interfaces.ExperimentConfiguration, error)) *ExperimentConfigurationHandlerInterface_Provide_Call {
	_c.Call.Return(run)
	return _c
}
