// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"os"

	"github.com/dgraph-io/ristretto/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewLocalCacheFactoryInterface creates a new instance of LocalCacheFactoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalCacheFactoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalCacheFactoryInterface {
	mock := &LocalCacheFactoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LocalCacheFactoryInterface is an autogenerated mock type for the LocalCacheFactoryInterface type
type LocalCacheFactoryInterface struct {
	mock.Mock
}

type LocalCacheFactoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LocalCacheFactoryInterface) EXPECT() *LocalCacheFactoryInterface_Expecter {
	return &LocalCacheFactoryInterface_Expecter{mock: &_m.Mock}
}

// ClearLocalCache provides a mock function for the type LocalCacheFactoryInterface
func (_mock *LocalCacheFactoryInterface) ClearLocalCache(cacheName string) {
	_mock.Called(cacheName)
	return
}

// LocalCacheFactoryInterface_ClearLocalCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearLocalCache'
type LocalCacheFactoryInterface_ClearLocalCache_Call struct {
	*mock.Call
}

// ClearLocalCache is a helper method to define mock.On call
//   - cacheName
func (_e *LocalCacheFactoryInterface_Expecter) ClearLocalCache(cacheName interface{}) *LocalCacheFactoryInterface_ClearLocalCache_Call {
	return &LocalCacheFactoryInterface_ClearLocalCache_Call{Call: _e.mock.On("ClearLocalCache", cacheName)}
}

func (_c *LocalCacheFactoryInterface_ClearLocalCache_Call) Run(run func(cacheName string)) *LocalCacheFactoryInterface_ClearLocalCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LocalCacheFactoryInterface_ClearLocalCache_Call) Return() *LocalCacheFactoryInterface_ClearLocalCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *LocalCacheFactoryInterface_ClearLocalCache_Call) RunAndReturn(run func(cacheName string)) *LocalCacheFactoryInterface_ClearLocalCache_Call {
	_c.Run(run)
	return _c
}

// GetFromLocalCache provides a mock function for the type LocalCacheFactoryInterface
func (_mock *LocalCacheFactoryInterface) GetFromLocalCache(cacheName string, key string) (any, bool) {
	ret := _mock.Called(cacheName, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFromLocalCache")
	}

	var r0 any
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (any, bool)); ok {
		return returnFunc(cacheName, key)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) any); ok {
		r0 = returnFunc(cacheName, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(cacheName, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// LocalCacheFactoryInterface_GetFromLocalCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFromLocalCache'
type LocalCacheFactoryInterface_GetFromLocalCache_Call struct {
	*mock.Call
}

// GetFromLocalCache is a helper method to define mock.On call
//   - cacheName
//   - key
func (_e *LocalCacheFactoryInterface_Expecter) GetFromLocalCache(cacheName interface{}, key interface{}) *LocalCacheFactoryInterface_GetFromLocalCache_Call {
	return &LocalCacheFactoryInterface_GetFromLocalCache_Call{Call: _e.mock.On("GetFromLocalCache", cacheName, key)}
}

func (_c *LocalCacheFactoryInterface_GetFromLocalCache_Call) Run(run func(cacheName string, key string)) *LocalCacheFactoryInterface_GetFromLocalCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *LocalCacheFactoryInterface_GetFromLocalCache_Call) Return(v any, b bool) *LocalCacheFactoryInterface_GetFromLocalCache_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *LocalCacheFactoryInterface_GetFromLocalCache_Call) RunAndReturn(run func(cacheName string, key string) (any, bool)) *LocalCacheFactoryInterface_GetFromLocalCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateCache provides a mock function for the type LocalCacheFactoryInterface
func (_mock *LocalCacheFactoryInterface) GetOrCreateCache(cacheName string) *ristretto.Cache[string, any] {
	ret := _mock.Called(cacheName)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateCache")
	}

	var r0 *ristretto.Cache[string, any]
	if returnFunc, ok := ret.Get(0).(func(string) *ristretto.Cache[string, any]); ok {
		r0 = returnFunc(cacheName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ristretto.Cache[string, any])
		}
	}
	return r0
}

// LocalCacheFactoryInterface_GetOrCreateCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateCache'
type LocalCacheFactoryInterface_GetOrCreateCache_Call struct {
	*mock.Call
}

// GetOrCreateCache is a helper method to define mock.On call
//   - cacheName
func (_e *LocalCacheFactoryInterface_Expecter) GetOrCreateCache(cacheName interface{}) *LocalCacheFactoryInterface_GetOrCreateCache_Call {
	return &LocalCacheFactoryInterface_GetOrCreateCache_Call{Call: _e.mock.On("GetOrCreateCache", cacheName)}
}

func (_c *LocalCacheFactoryInterface_GetOrCreateCache_Call) Run(run func(cacheName string)) *LocalCacheFactoryInterface_GetOrCreateCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LocalCacheFactoryInterface_GetOrCreateCache_Call) Return(cache *ristretto.Cache[string, any]) *LocalCacheFactoryInterface_GetOrCreateCache_Call {
	_c.Call.Return(cache)
	return _c
}

func (_c *LocalCacheFactoryInterface_GetOrCreateCache_Call) RunAndReturn(run func(cacheName string) *ristretto.Cache[string, any]) *LocalCacheFactoryInterface_GetOrCreateCache_Call {
	_c.Call.Return(run)
	return _c
}

// PutToLocalCache provides a mock function for the type LocalCacheFactoryInterface
func (_mock *LocalCacheFactoryInterface) PutToLocalCache(cacheName string, key string, value any) bool {
	ret := _mock.Called(cacheName, key, value)

	if len(ret) == 0 {
		panic("no return value specified for PutToLocalCache")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string, any) bool); ok {
		r0 = returnFunc(cacheName, key, value)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// LocalCacheFactoryInterface_PutToLocalCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutToLocalCache'
type LocalCacheFactoryInterface_PutToLocalCache_Call struct {
	*mock.Call
}

// PutToLocalCache is a helper method to define mock.On call
//   - cacheName
//   - key
//   - value
func (_e *LocalCacheFactoryInterface_Expecter) PutToLocalCache(cacheName interface{}, key interface{}, value interface{}) *LocalCacheFactoryInterface_PutToLocalCache_Call {
	return &LocalCacheFactoryInterface_PutToLocalCache_Call{Call: _e.mock.On("PutToLocalCache", cacheName, key, value)}
}

func (_c *LocalCacheFactoryInterface_PutToLocalCache_Call) Run(run func(cacheName string, key string, value any)) *LocalCacheFactoryInterface_PutToLocalCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *LocalCacheFactoryInterface_PutToLocalCache_Call) Return(b bool) *LocalCacheFactoryInterface_PutToLocalCache_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *LocalCacheFactoryInterface_PutToLocalCache_Call) RunAndReturn(run func(cacheName string, key string, value any) bool) *LocalCacheFactoryInterface_PutToLocalCache_Call {
	_c.Call.Return(run)
	return _c
}

// PutToLocalCacheWithTTL provides a mock function for the type LocalCacheFactoryInterface
func (_mock *LocalCacheFactoryInterface) PutToLocalCacheWithTTL(cacheName string, key string, value any, ttlSeconds int64) bool {
	ret := _mock.Called(cacheName, key, value, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for PutToLocalCacheWithTTL")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string, any, int64) bool); ok {
		r0 = returnFunc(cacheName, key, value, ttlSeconds)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutToLocalCacheWithTTL'
type LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call struct {
	*mock.Call
}

// PutToLocalCacheWithTTL is a helper method to define mock.On call
//   - cacheName
//   - key
//   - value
//   - ttlSeconds
func (_e *LocalCacheFactoryInterface_Expecter) PutToLocalCacheWithTTL(cacheName interface{}, key interface{}, value interface{}, ttlSeconds interface{}) *LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call {
	return &LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call{Call: _e.mock.On("PutToLocalCacheWithTTL", cacheName, key, value, ttlSeconds)}
}

func (_c *LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call) Run(run func(cacheName string, key string, value any, ttlSeconds int64)) *LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(any), args[3].(int64))
	})
	return _c
}

func (_c *LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call) Return(b bool) *LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call) RunAndReturn(run func(cacheName string, key string, value any, ttlSeconds int64) bool) *LocalCacheFactoryInterface_PutToLocalCacheWithTTL_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldRefresh provides a mock function for the type LocalCacheFactoryInterface
func (_mock *LocalCacheFactoryInterface) ShouldRefresh(fileIdentifierCacheKey string, fileIdentifier string) bool {
	ret := _mock.Called(fileIdentifierCacheKey, fileIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for ShouldRefresh")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(fileIdentifierCacheKey, fileIdentifier)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// LocalCacheFactoryInterface_ShouldRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldRefresh'
type LocalCacheFactoryInterface_ShouldRefresh_Call struct {
	*mock.Call
}

// ShouldRefresh is a helper method to define mock.On call
//   - fileIdentifierCacheKey
//   - fileIdentifier
func (_e *LocalCacheFactoryInterface_Expecter) ShouldRefresh(fileIdentifierCacheKey interface{}, fileIdentifier interface{}) *LocalCacheFactoryInterface_ShouldRefresh_Call {
	return &LocalCacheFactoryInterface_ShouldRefresh_Call{Call: _e.mock.On("ShouldRefresh", fileIdentifierCacheKey, fileIdentifier)}
}

func (_c *LocalCacheFactoryInterface_ShouldRefresh_Call) Run(run func(fileIdentifierCacheKey string, fileIdentifier string)) *LocalCacheFactoryInterface_ShouldRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *LocalCacheFactoryInterface_ShouldRefresh_Call) Return(b bool) *LocalCacheFactoryInterface_ShouldRefresh_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *LocalCacheFactoryInterface_ShouldRefresh_Call) RunAndReturn(run func(fileIdentifierCacheKey string, fileIdentifier string) bool) *LocalCacheFactoryInterface_ShouldRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldRefreshLocal provides a mock function for the type LocalCacheFactoryInterface
func (_mock *LocalCacheFactoryInterface) ShouldRefreshLocal(fileIdentifierCacheKey string, filePointer *os.File) bool {
	ret := _mock.Called(fileIdentifierCacheKey, filePointer)

	if len(ret) == 0 {
		panic("no return value specified for ShouldRefreshLocal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, *os.File) bool); ok {
		r0 = returnFunc(fileIdentifierCacheKey, filePointer)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// LocalCacheFactoryInterface_ShouldRefreshLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldRefreshLocal'
type LocalCacheFactoryInterface_ShouldRefreshLocal_Call struct {
	*mock.Call
}

// ShouldRefreshLocal is a helper method to define mock.On call
//   - fileIdentifierCacheKey
//   - filePointer
func (_e *LocalCacheFactoryInterface_Expecter) ShouldRefreshLocal(fileIdentifierCacheKey interface{}, filePointer interface{}) *LocalCacheFactoryInterface_ShouldRefreshLocal_Call {
	return &LocalCacheFactoryInterface_ShouldRefreshLocal_Call{Call: _e.mock.On("ShouldRefreshLocal", fileIdentifierCacheKey, filePointer)}
}

func (_c *LocalCacheFactoryInterface_ShouldRefreshLocal_Call) Run(run func(fileIdentifierCacheKey string, filePointer *os.File)) *LocalCacheFactoryInterface_ShouldRefreshLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*os.File))
	})
	return _c
}

func (_c *LocalCacheFactoryInterface_ShouldRefreshLocal_Call) Return(b bool) *LocalCacheFactoryInterface_ShouldRefreshLocal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *LocalCacheFactoryInterface_ShouldRefreshLocal_Call) RunAndReturn(run func(fileIdentifierCacheKey string, filePointer *os.File) bool) *LocalCacheFactoryInterface_ShouldRefreshLocal_Call {
	_c.Call.Return(run)
	return _c
}
