// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"github.com/dgraph-io/ristretto/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewLocalCacheRegistryInterface creates a new instance of LocalCacheRegistryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalCacheRegistryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalCacheRegistryInterface {
	mock := &LocalCacheRegistryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LocalCacheRegistryInterface is an autogenerated mock type for the LocalCacheRegistryInterface type
type LocalCacheRegistryInterface struct {
	mock.Mock
}

type LocalCacheRegistryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LocalCacheRegistryInterface) EXPECT() *LocalCacheRegistryInterface_Expecter {
	return &LocalCacheRegistryInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type LocalCacheRegistryInterface
func (_mock *LocalCacheRegistryInterface) Get(cacheName string) (*ristretto.Cache[string, any], bool) {
	ret := _mock.Called(cacheName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ristretto.Cache[string, any]
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*ristretto.Cache[string, any], bool)); ok {
		return returnFunc(cacheName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ristretto.Cache[string, any]); ok {
		r0 = returnFunc(cacheName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ristretto.Cache[string, any])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(cacheName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// LocalCacheRegistryInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type LocalCacheRegistryInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - cacheName
func (_e *LocalCacheRegistryInterface_Expecter) Get(cacheName interface{}) *LocalCacheRegistryInterface_Get_Call {
	return &LocalCacheRegistryInterface_Get_Call{Call: _e.mock.On("Get", cacheName)}
}

func (_c *LocalCacheRegistryInterface_Get_Call) Run(run func(cacheName string)) *LocalCacheRegistryInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LocalCacheRegistryInterface_Get_Call) Return(cache *ristretto.Cache[string, any], b bool) *LocalCacheRegistryInterface_Get_Call {
	_c.Call.Return(cache, b)
	return _c
}

func (_c *LocalCacheRegistryInterface_Get_Call) RunAndReturn(run func(cacheName string) (*ristretto.Cache[string, any], bool)) *LocalCacheRegistryInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type LocalCacheRegistryInterface
func (_mock *LocalCacheRegistryInterface) Register(cacheName string, cache *ristretto.Cache[string, any]) {
	_mock.Called(cacheName, cache)
	return
}

// LocalCacheRegistryInterface_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type LocalCacheRegistryInterface_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - cacheName
//   - cache
func (_e *LocalCacheRegistryInterface_Expecter) Register(cacheName interface{}, cache interface{}) *LocalCacheRegistryInterface_Register_Call {
	return &LocalCacheRegistryInterface_Register_Call{Call: _e.mock.On("Register", cacheName, cache)}
}

func (_c *LocalCacheRegistryInterface_Register_Call) Run(run func(cacheName string, cache *ristretto.Cache[string, any])) *LocalCacheRegistryInterface_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*ristretto.Cache[string, any]))
	})
	return _c
}

func (_c *LocalCacheRegistryInterface_Register_Call) Return() *LocalCacheRegistryInterface_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *LocalCacheRegistryInterface_Register_Call) RunAndReturn(run func(cacheName string, cache *ristretto.Cache[string, any])) *LocalCacheRegistryInterface_Register_Call {
	_c.Run(run)
	return _c
}
