// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
	"golang.a2z.com/demanddriventrafficevaluator/interfaces"
)

// NewModelConfigurationHandlerInterface creates a new instance of ModelConfigurationHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelConfigurationHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelConfigurationHandlerInterface {
	mock := &ModelConfigurationHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ModelConfigurationHandlerInterface is an autogenerated mock type for the ModelConfigurationHandlerInterface type
type ModelConfigurationHandlerInterface struct {
	mock.Mock
}

type ModelConfigurationHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelConfigurationHandlerInterface) EXPECT() *ModelConfigurationHandlerInterface_Expecter {
	return &ModelConfigurationHandlerInterface_Expecter{mock: &_m.Mock}
}

// GetAllUniqueFeatureFields provides a mock function for the type ModelConfigurationHandlerInterface
func (_mock *ModelConfigurationHandlerInterface) GetAllUniqueFeatureFields() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUniqueFeatureFields")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUniqueFeatureFields'
type ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call struct {
	*mock.Call
}

// GetAllUniqueFeatureFields is a helper method to define mock.On call
func (_e *ModelConfigurationHandlerInterface_Expecter) GetAllUniqueFeatureFields() *ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call {
	return &ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call{Call: _e.mock.On("GetAllUniqueFeatureFields")}
}

func (_c *ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call) Run(run func()) *ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call) Return(strings []string, err error) *ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call) RunAndReturn(run func() ([]string, error)) *ModelConfigurationHandlerInterface_GetAllUniqueFeatureFields_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type ModelConfigurationHandlerInterface
func (_mock *ModelConfigurationHandlerInterface) Load() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ModelConfigurationHandlerInterface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type ModelConfigurationHandlerInterface_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *ModelConfigurationHandlerInterface_Expecter) Load() *ModelConfigurationHandlerInterface_Load_Call {
	return &ModelConfigurationHandlerInterface_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *ModelConfigurationHandlerInterface_Load_Call) Run(run func()) *ModelConfigurationHandlerInterface_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelConfigurationHandlerInterface_Load_Call) Return(b bool, err error) *ModelConfigurationHandlerInterface_Load_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ModelConfigurationHandlerInterface_Load_Call) RunAndReturn(run func() (bool, error)) *ModelConfigurationHandlerInterface_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Provide provides a mock function for the type ModelConfigurationHandlerInterface
func (_mock *ModelConfigurationHandlerInterface) Provide() (*interfaces.ModelConfiguration, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 *interfaces.ModelConfiguration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*interfaces.ModelConfiguration, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *interfaces.ModelConfiguration); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ModelConfiguration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ModelConfigurationHandlerInterface_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type ModelConfigurationHandlerInterface_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
func (_e *ModelConfigurationHandlerInterface_Expecter) Provide() *ModelConfigurationHandlerInterface_Provide_Call {
	return &ModelConfigurationHandlerInterface_Provide_Call{Call: _e.mock.On("Provide")}
}

func (_c *ModelConfigurationHandlerInterface_Provide_Call) Run(run func()) *ModelConfigurationHandlerInterface_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelConfigurationHandlerInterface_Provide_Call) Return(modelConfiguration *interfaces.ModelConfiguration, err error) *ModelConfigurationHandlerInterface_Provide_Call {
	_c.Call.Return(modelConfiguration, err)
	return _c
}

func (_c *ModelConfigurationHandlerInterface_Provide_Call) RunAndReturn(run func() (*interfaces.ModelConfiguration, error)) *ModelConfigurationHandlerInterface_Provide_Call {
	_c.Call.Return(run)
	return _c
}
