// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
	"golang.a2z.com/demanddriventrafficevaluator/interfaces"
)

// NewModelEvaluator creates a new instance of ModelEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelEvaluator {
	mock := &ModelEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ModelEvaluator is an autogenerated mock type for the ModelEvaluator type
type ModelEvaluator struct {
	mock.Mock
}

type ModelEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelEvaluator) EXPECT() *ModelEvaluator_Expecter {
	return &ModelEvaluator_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type ModelEvaluator
func (_mock *ModelEvaluator) Evaluate(input interfaces.ModelEvaluatorInput) (*interfaces.ModelEvaluatorOutput, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 *interfaces.ModelEvaluatorOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interfaces.ModelEvaluatorInput) (*interfaces.ModelEvaluatorOutput, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(interfaces.ModelEvaluatorInput) *interfaces.ModelEvaluatorOutput); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ModelEvaluatorOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interfaces.ModelEvaluatorInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ModelEvaluator_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type ModelEvaluator_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - input
func (_e *ModelEvaluator_Expecter) Evaluate(input interface{}) *ModelEvaluator_Evaluate_Call {
	return &ModelEvaluator_Evaluate_Call{Call: _e.mock.On("Evaluate", input)}
}

func (_c *ModelEvaluator_Evaluate_Call) Run(run func(input interfaces.ModelEvaluatorInput)) *ModelEvaluator_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaces.ModelEvaluatorInput))
	})
	return _c
}

func (_c *ModelEvaluator_Evaluate_Call) Return(modelEvaluatorOutput *interfaces.ModelEvaluatorOutput, err error) *ModelEvaluator_Evaluate_Call {
	_c.Call.Return(modelEvaluatorOutput, err)
	return _c
}

func (_c *ModelEvaluator_Evaluate_Call) RunAndReturn(run func(input interfaces.ModelEvaluatorInput) (*interfaces.ModelEvaluatorOutput, error)) *ModelEvaluator_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}
