// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
	"golang.a2z.com/demanddriventrafficevaluator/interfaces"
)

// NewModelResultHandlerInterface creates a new instance of ModelResultHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelResultHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelResultHandlerInterface {
	mock := &ModelResultHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ModelResultHandlerInterface is an autogenerated mock type for the ModelResultHandlerInterface type
type ModelResultHandlerInterface struct {
	mock.Mock
}

type ModelResultHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelResultHandlerInterface) EXPECT() *ModelResultHandlerInterface_Expecter {
	return &ModelResultHandlerInterface_Expecter{mock: &_m.Mock}
}

// BuildKey provides a mock function for the type ModelResultHandlerInterface
func (_mock *ModelResultHandlerInterface) BuildKey(modelFeatures []interfaces.ModelFeature) string {
	ret := _mock.Called(modelFeatures)

	if len(ret) == 0 {
		panic("no return value specified for BuildKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]interfaces.ModelFeature) string); ok {
		r0 = returnFunc(modelFeatures)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ModelResultHandlerInterface_BuildKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildKey'
type ModelResultHandlerInterface_BuildKey_Call struct {
	*mock.Call
}

// BuildKey is a helper method to define mock.On call
//   - modelFeatures
func (_e *ModelResultHandlerInterface_Expecter) BuildKey(modelFeatures interface{}) *ModelResultHandlerInterface_BuildKey_Call {
	return &ModelResultHandlerInterface_BuildKey_Call{Call: _e.mock.On("BuildKey", modelFeatures)}
}

func (_c *ModelResultHandlerInterface_BuildKey_Call) Run(run func(modelFeatures []interfaces.ModelFeature)) *ModelResultHandlerInterface_BuildKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]interfaces.ModelFeature))
	})
	return _c
}

func (_c *ModelResultHandlerInterface_BuildKey_Call) Return(s string) *ModelResultHandlerInterface_BuildKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ModelResultHandlerInterface_BuildKey_Call) RunAndReturn(run func(modelFeatures []interfaces.ModelFeature) string) *ModelResultHandlerInterface_BuildKey_Call {
	_c.Call.Return(run)
	return _c
}

// BuildModelResultFileName provides a mock function for the type ModelResultHandlerInterface
func (_mock *ModelResultHandlerInterface) BuildModelResultFileName(sspIdentifier string, modelIdentifier string) string {
	ret := _mock.Called(sspIdentifier, modelIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for BuildModelResultFileName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(sspIdentifier, modelIdentifier)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ModelResultHandlerInterface_BuildModelResultFileName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildModelResultFileName'
type ModelResultHandlerInterface_BuildModelResultFileName_Call struct {
	*mock.Call
}

// BuildModelResultFileName is a helper method to define mock.On call
//   - sspIdentifier
//   - modelIdentifier
func (_e *ModelResultHandlerInterface_Expecter) BuildModelResultFileName(sspIdentifier interface{}, modelIdentifier interface{}) *ModelResultHandlerInterface_BuildModelResultFileName_Call {
	return &ModelResultHandlerInterface_BuildModelResultFileName_Call{Call: _e.mock.On("BuildModelResultFileName", sspIdentifier, modelIdentifier)}
}

func (_c *ModelResultHandlerInterface_BuildModelResultFileName_Call) Run(run func(sspIdentifier string, modelIdentifier string)) *ModelResultHandlerInterface_BuildModelResultFileName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ModelResultHandlerInterface_BuildModelResultFileName_Call) Return(s string) *ModelResultHandlerInterface_BuildModelResultFileName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ModelResultHandlerInterface_BuildModelResultFileName_Call) RunAndReturn(run func(sspIdentifier string, modelIdentifier string) string) *ModelResultHandlerInterface_BuildModelResultFileName_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type ModelResultHandlerInterface
func (_mock *ModelResultHandlerInterface) Load(sspIdentifier string) error {
	ret := _mock.Called(sspIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(sspIdentifier)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ModelResultHandlerInterface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type ModelResultHandlerInterface_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - sspIdentifier
func (_e *ModelResultHandlerInterface_Expecter) Load(sspIdentifier interface{}) *ModelResultHandlerInterface_Load_Call {
	return &ModelResultHandlerInterface_Load_Call{Call: _e.mock.On("Load", sspIdentifier)}
}

func (_c *ModelResultHandlerInterface_Load_Call) Run(run func(sspIdentifier string)) *ModelResultHandlerInterface_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ModelResultHandlerInterface_Load_Call) Return(err error) *ModelResultHandlerInterface_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ModelResultHandlerInterface_Load_Call) RunAndReturn(run func(sspIdentifier string) error) *ModelResultHandlerInterface_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Provide provides a mock function for the type ModelResultHandlerInterface
func (_mock *ModelResultHandlerInterface) Provide(modelIdentifier string, features []interfaces.ModelFeature, defaultValue float32) (*interfaces.ModelResult, error) {
	ret := _mock.Called(modelIdentifier, features, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 *interfaces.ModelResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []interfaces.ModelFeature, float32) (*interfaces.ModelResult, error)); ok {
		return returnFunc(modelIdentifier, features, defaultValue)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []interfaces.ModelFeature, float32) *interfaces.ModelResult); ok {
		r0 = returnFunc(modelIdentifier, features, defaultValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ModelResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []interfaces.ModelFeature, float32) error); ok {
		r1 = returnFunc(modelIdentifier, features, defaultValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ModelResultHandlerInterface_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type ModelResultHandlerInterface_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
//   - modelIdentifier
//   - features
//   - defaultValue
func (_e *ModelResultHandlerInterface_Expecter) Provide(modelIdentifier interface{}, features interface{}, defaultValue interface{}) *ModelResultHandlerInterface_Provide_Call {
	return &ModelResultHandlerInterface_Provide_Call{Call: _e.mock.On("Provide", modelIdentifier, features, defaultValue)}
}

func (_c *ModelResultHandlerInterface_Provide_Call) Run(run func(modelIdentifier string, features []interfaces.ModelFeature, defaultValue float32)) *ModelResultHandlerInterface_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]interfaces.ModelFeature), args[2].(float32))
	})
	return _c
}

func (_c *ModelResultHandlerInterface_Provide_Call) Return(modelResult *interfaces.ModelResult, err error) *ModelResultHandlerInterface_Provide_Call {
	_c.Call.Return(modelResult, err)
	return _c
}

func (_c *ModelResultHandlerInterface_Provide_Call) RunAndReturn(run func(modelIdentifier string, features []interfaces.ModelFeature, defaultValue float32) (*interfaces.ModelResult, error)) *ModelResultHandlerInterface_Provide_Call {
	_c.Call.Return(run)
	return _c
}
