// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTask creates a new instance of Task. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *Task {
	mock := &Task{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Task is an autogenerated mock type for the Task type
type Task struct {
	mock.Mock
}

type Task_Expecter struct {
	mock *mock.Mock
}

func (_m *Task) EXPECT() *Task_Expecter {
	return &Task_Expecter{mock: &_m.Mock}
}

// ExecuteTask provides a mock function for the type Task
func (_mock *Task) ExecuteTask() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Task_ExecuteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTask'
type Task_ExecuteTask_Call struct {
	*mock.Call
}

// ExecuteTask is a helper method to define mock.On call
func (_e *Task_Expecter) ExecuteTask() *Task_ExecuteTask_Call {
	return &Task_ExecuteTask_Call{Call: _e.mock.On("ExecuteTask")}
}

func (_c *Task_ExecuteTask_Call) Run(run func()) *Task_ExecuteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Task_ExecuteTask_Call) Return(err error) *Task_ExecuteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Task_ExecuteTask_Call) RunAndReturn(run func() error) *Task_ExecuteTask_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type Task
func (_mock *Task) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Task_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Task_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *Task_Expecter) Run() *Task_Run_Call {
	return &Task_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *Task_Run_Call) Run(run func()) *Task_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Task_Run_Call) Return(err error) *Task_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Task_Run_Call) RunAndReturn(run func() error) *Task_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Task
func (_mock *Task) Stop() {
	_mock.Called()
	return
}

// Task_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Task_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Task_Expecter) Stop() *Task_Stop_Call {
	return &Task_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Task_Stop_Call) Run(run func()) *Task_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Task_Stop_Call) Return() *Task_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Task_Stop_Call) RunAndReturn(run func()) *Task_Stop_Call {
	_c.Run(run)
	return _c
}
