// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewTimeProvider creates a new instance of TimeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeProvider {
	mock := &TimeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TimeProvider is an autogenerated mock type for the TimeProvider type
type TimeProvider struct {
	mock.Mock
}

type TimeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeProvider) EXPECT() *TimeProvider_Expecter {
	return &TimeProvider_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type TimeProvider
func (_mock *TimeProvider) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// TimeProvider_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type TimeProvider_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *TimeProvider_Expecter) Now() *TimeProvider_Now_Call {
	return &TimeProvider_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *TimeProvider_Now_Call) Run(run func()) *TimeProvider_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TimeProvider_Now_Call) Return(time1 time.Time) *TimeProvider_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *TimeProvider_Now_Call) RunAndReturn(run func() time.Time) *TimeProvider_Now_Call {
	_c.Call.Return(run)
	return _c
}
