// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
	"golang.a2z.com/demanddriventrafficevaluator/interfaces"
)

// NewTrafficAllocationContextInterface creates a new instance of TrafficAllocationContextInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrafficAllocationContextInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrafficAllocationContextInterface {
	mock := &TrafficAllocationContextInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TrafficAllocationContextInterface is an autogenerated mock type for the TrafficAllocationContextInterface type
type TrafficAllocationContextInterface struct {
	mock.Mock
}

type TrafficAllocationContextInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *TrafficAllocationContextInterface) EXPECT() *TrafficAllocationContextInterface_Expecter {
	return &TrafficAllocationContextInterface_Expecter{mock: &_m.Mock}
}

// GetExperimentArrangement provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetExperimentArrangement() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExperimentArrangement")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// TrafficAllocationContextInterface_GetExperimentArrangement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperimentArrangement'
type TrafficAllocationContextInterface_GetExperimentArrangement_Call struct {
	*mock.Call
}

// GetExperimentArrangement is a helper method to define mock.On call
func (_e *TrafficAllocationContextInterface_Expecter) GetExperimentArrangement() *TrafficAllocationContextInterface_GetExperimentArrangement_Call {
	return &TrafficAllocationContextInterface_GetExperimentArrangement_Call{Call: _e.mock.On("GetExperimentArrangement")}
}

func (_c *TrafficAllocationContextInterface_GetExperimentArrangement_Call) Run(run func()) *TrafficAllocationContextInterface_GetExperimentArrangement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentArrangement_Call) Return(stringToString map[string]string) *TrafficAllocationContextInterface_GetExperimentArrangement_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentArrangement_Call) RunAndReturn(run func() map[string]string) *TrafficAllocationContextInterface_GetExperimentArrangement_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperimentDefinition provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetExperimentDefinition(experimentName string) interfaces.ExperimentDefinition {
	ret := _mock.Called(experimentName)

	if len(ret) == 0 {
		panic("no return value specified for GetExperimentDefinition")
	}

	var r0 interfaces.ExperimentDefinition
	if returnFunc, ok := ret.Get(0).(func(string) interfaces.ExperimentDefinition); ok {
		r0 = returnFunc(experimentName)
	} else {
		r0 = ret.Get(0).(interfaces.ExperimentDefinition)
	}
	return r0
}

// TrafficAllocationContextInterface_GetExperimentDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperimentDefinition'
type TrafficAllocationContextInterface_GetExperimentDefinition_Call struct {
	*mock.Call
}

// GetExperimentDefinition is a helper method to define mock.On call
//   - experimentName
func (_e *TrafficAllocationContextInterface_Expecter) GetExperimentDefinition(experimentName interface{}) *TrafficAllocationContextInterface_GetExperimentDefinition_Call {
	return &TrafficAllocationContextInterface_GetExperimentDefinition_Call{Call: _e.mock.On("GetExperimentDefinition", experimentName)}
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinition_Call) Run(run func(experimentName string)) *TrafficAllocationContextInterface_GetExperimentDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinition_Call) Return(experimentDefinition interfaces.ExperimentDefinition) *TrafficAllocationContextInterface_GetExperimentDefinition_Call {
	_c.Call.Return(experimentDefinition)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinition_Call) RunAndReturn(run func(experimentName string) interfaces.ExperimentDefinition) *TrafficAllocationContextInterface_GetExperimentDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperimentDefinitionByModel provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetExperimentDefinitionByModel(model string) interfaces.ExperimentDefinition {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for GetExperimentDefinitionByModel")
	}

	var r0 interfaces.ExperimentDefinition
	if returnFunc, ok := ret.Get(0).(func(string) interfaces.ExperimentDefinition); ok {
		r0 = returnFunc(model)
	} else {
		r0 = ret.Get(0).(interfaces.ExperimentDefinition)
	}
	return r0
}

// TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperimentDefinitionByModel'
type TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call struct {
	*mock.Call
}

// GetExperimentDefinitionByModel is a helper method to define mock.On call
//   - model
func (_e *TrafficAllocationContextInterface_Expecter) GetExperimentDefinitionByModel(model interface{}) *TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call {
	return &TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call{Call: _e.mock.On("GetExperimentDefinitionByModel", model)}
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call) Run(run func(model string)) *TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call) Return(experimentDefinition interfaces.ExperimentDefinition) *TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call {
	_c.Call.Return(experimentDefinition)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call) RunAndReturn(run func(model string) interfaces.ExperimentDefinition) *TrafficAllocationContextInterface_GetExperimentDefinitionByModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperimentDefinitionByType provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetExperimentDefinitionByType(typeStr string) (*interfaces.ExperimentDefinition, error) {
	ret := _mock.Called(typeStr)

	if len(ret) == 0 {
		panic("no return value specified for GetExperimentDefinitionByType")
	}

	var r0 *interfaces.ExperimentDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*interfaces.ExperimentDefinition, error)); ok {
		return returnFunc(typeStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *interfaces.ExperimentDefinition); ok {
		r0 = returnFunc(typeStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ExperimentDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(typeStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperimentDefinitionByType'
type TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call struct {
	*mock.Call
}

// GetExperimentDefinitionByType is a helper method to define mock.On call
//   - typeStr
func (_e *TrafficAllocationContextInterface_Expecter) GetExperimentDefinitionByType(typeStr interface{}) *TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call {
	return &TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call{Call: _e.mock.On("GetExperimentDefinitionByType", typeStr)}
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call) Run(run func(typeStr string)) *TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call) Return(experimentDefinition *interfaces.ExperimentDefinition, err error) *TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call {
	_c.Call.Return(experimentDefinition, err)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call) RunAndReturn(run func(typeStr string) (*interfaces.ExperimentDefinition, error)) *TrafficAllocationContextInterface_GetExperimentDefinitionByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelIdentifiers provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetModelIdentifiers() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetModelIdentifiers")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// TrafficAllocationContextInterface_GetModelIdentifiers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelIdentifiers'
type TrafficAllocationContextInterface_GetModelIdentifiers_Call struct {
	*mock.Call
}

// GetModelIdentifiers is a helper method to define mock.On call
func (_e *TrafficAllocationContextInterface_Expecter) GetModelIdentifiers() *TrafficAllocationContextInterface_GetModelIdentifiers_Call {
	return &TrafficAllocationContextInterface_GetModelIdentifiers_Call{Call: _e.mock.On("GetModelIdentifiers")}
}

func (_c *TrafficAllocationContextInterface_GetModelIdentifiers_Call) Run(run func()) *TrafficAllocationContextInterface_GetModelIdentifiers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetModelIdentifiers_Call) Return(strings []string) *TrafficAllocationContextInterface_GetModelIdentifiers_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetModelIdentifiers_Call) RunAndReturn(run func() []string) *TrafficAllocationContextInterface_GetModelIdentifiers_Call {
	_c.Call.Return(run)
	return _c
}

// GetModelsByExperiment provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetModelsByExperiment() map[string][]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetModelsByExperiment")
	}

	var r0 map[string][]string
	if returnFunc, ok := ret.Get(0).(func() map[string][]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	return r0
}

// TrafficAllocationContextInterface_GetModelsByExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelsByExperiment'
type TrafficAllocationContextInterface_GetModelsByExperiment_Call struct {
	*mock.Call
}

// GetModelsByExperiment is a helper method to define mock.On call
func (_e *TrafficAllocationContextInterface_Expecter) GetModelsByExperiment() *TrafficAllocationContextInterface_GetModelsByExperiment_Call {
	return &TrafficAllocationContextInterface_GetModelsByExperiment_Call{Call: _e.mock.On("GetModelsByExperiment")}
}

func (_c *TrafficAllocationContextInterface_GetModelsByExperiment_Call) Run(run func()) *TrafficAllocationContextInterface_GetModelsByExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetModelsByExperiment_Call) Return(stringToStrings map[string][]string) *TrafficAllocationContextInterface_GetModelsByExperiment_Call {
	_c.Call.Return(stringToStrings)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetModelsByExperiment_Call) RunAndReturn(run func() map[string][]string) *TrafficAllocationContextInterface_GetModelsByExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// GetTreatmentCode provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetTreatmentCode(experimentName string) string {
	ret := _mock.Called(experimentName)

	if len(ret) == 0 {
		panic("no return value specified for GetTreatmentCode")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(experimentName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// TrafficAllocationContextInterface_GetTreatmentCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTreatmentCode'
type TrafficAllocationContextInterface_GetTreatmentCode_Call struct {
	*mock.Call
}

// GetTreatmentCode is a helper method to define mock.On call
//   - experimentName
func (_e *TrafficAllocationContextInterface_Expecter) GetTreatmentCode(experimentName interface{}) *TrafficAllocationContextInterface_GetTreatmentCode_Call {
	return &TrafficAllocationContextInterface_GetTreatmentCode_Call{Call: _e.mock.On("GetTreatmentCode", experimentName)}
}

func (_c *TrafficAllocationContextInterface_GetTreatmentCode_Call) Run(run func(experimentName string)) *TrafficAllocationContextInterface_GetTreatmentCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetTreatmentCode_Call) Return(s string) *TrafficAllocationContextInterface_GetTreatmentCode_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetTreatmentCode_Call) RunAndReturn(run func(experimentName string) string) *TrafficAllocationContextInterface_GetTreatmentCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetTreatmentCodeInInt provides a mock function for the type TrafficAllocationContextInterface
func (_mock *TrafficAllocationContextInterface) GetTreatmentCodeInInt(experimentName string) int8 {
	ret := _mock.Called(experimentName)

	if len(ret) == 0 {
		panic("no return value specified for GetTreatmentCodeInInt")
	}

	var r0 int8
	if returnFunc, ok := ret.Get(0).(func(string) int8); ok {
		r0 = returnFunc(experimentName)
	} else {
		r0 = ret.Get(0).(int8)
	}
	return r0
}

// TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTreatmentCodeInInt'
type TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call struct {
	*mock.Call
}

// GetTreatmentCodeInInt is a helper method to define mock.On call
//   - experimentName
func (_e *TrafficAllocationContextInterface_Expecter) GetTreatmentCodeInInt(experimentName interface{}) *TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call {
	return &TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call{Call: _e.mock.On("GetTreatmentCodeInInt", experimentName)}
}

func (_c *TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call) Run(run func(experimentName string)) *TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call) Return(n int8) *TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call) RunAndReturn(run func(experimentName string) int8) *TrafficAllocationContextInterface_GetTreatmentCodeInInt_Call {
	_c.Call.Return(run)
	return _c
}
