// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
	"golang.a2z.com/demanddriventrafficevaluator/interfaces"
)

// NewTrafficAllocatorInterface creates a new instance of TrafficAllocatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrafficAllocatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrafficAllocatorInterface {
	mock := &TrafficAllocatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TrafficAllocatorInterface is an autogenerated mock type for the TrafficAllocatorInterface type
type TrafficAllocatorInterface struct {
	mock.Mock
}

type TrafficAllocatorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *TrafficAllocatorInterface) EXPECT() *TrafficAllocatorInterface_Expecter {
	return &TrafficAllocatorInterface_Expecter{mock: &_m.Mock}
}

// GetTrafficAllocationContext provides a mock function for the type TrafficAllocatorInterface
func (_mock *TrafficAllocatorInterface) GetTrafficAllocationContext() interfaces.TrafficAllocationContextInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTrafficAllocationContext")
	}

	var r0 interfaces.TrafficAllocationContextInterface
	if returnFunc, ok := ret.Get(0).(func() interfaces.TrafficAllocationContextInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.TrafficAllocationContextInterface)
		}
	}
	return r0
}

// TrafficAllocatorInterface_GetTrafficAllocationContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrafficAllocationContext'
type TrafficAllocatorInterface_GetTrafficAllocationContext_Call struct {
	*mock.Call
}

// GetTrafficAllocationContext is a helper method to define mock.On call
func (_e *TrafficAllocatorInterface_Expecter) GetTrafficAllocationContext() *TrafficAllocatorInterface_GetTrafficAllocationContext_Call {
	return &TrafficAllocatorInterface_GetTrafficAllocationContext_Call{Call: _e.mock.On("GetTrafficAllocationContext")}
}

func (_c *TrafficAllocatorInterface_GetTrafficAllocationContext_Call) Run(run func()) *TrafficAllocatorInterface_GetTrafficAllocationContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrafficAllocatorInterface_GetTrafficAllocationContext_Call) Return(trafficAllocationContextInterface interfaces.TrafficAllocationContextInterface) *TrafficAllocatorInterface_GetTrafficAllocationContext_Call {
	_c.Call.Return(trafficAllocationContextInterface)
	return _c
}

func (_c *TrafficAllocatorInterface_GetTrafficAllocationContext_Call) RunAndReturn(run func() interfaces.TrafficAllocationContextInterface) *TrafficAllocatorInterface_GetTrafficAllocationContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetTreatmentCode provides a mock function for the type TrafficAllocatorInterface
func (_mock *TrafficAllocatorInterface) GetTreatmentCode(thresholds []uint32, treatments []interfaces.Treatment) (string, error) {
	ret := _mock.Called(thresholds, treatments)

	if len(ret) == 0 {
		panic("no return value specified for GetTreatmentCode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]uint32, []interfaces.Treatment) (string, error)); ok {
		return returnFunc(thresholds, treatments)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint32, []interfaces.Treatment) string); ok {
		r0 = returnFunc(thresholds, treatments)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]uint32, []interfaces.Treatment) error); ok {
		r1 = returnFunc(thresholds, treatments)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TrafficAllocatorInterface_GetTreatmentCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTreatmentCode'
type TrafficAllocatorInterface_GetTreatmentCode_Call struct {
	*mock.Call
}

// GetTreatmentCode is a helper method to define mock.On call
//   - thresholds
//   - treatments
func (_e *TrafficAllocatorInterface_Expecter) GetTreatmentCode(thresholds interface{}, treatments interface{}) *TrafficAllocatorInterface_GetTreatmentCode_Call {
	return &TrafficAllocatorInterface_GetTreatmentCode_Call{Call: _e.mock.On("GetTreatmentCode", thresholds, treatments)}
}

func (_c *TrafficAllocatorInterface_GetTreatmentCode_Call) Run(run func(thresholds []uint32, treatments []interfaces.Treatment)) *TrafficAllocatorInterface_GetTreatmentCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]uint32), args[1].([]interfaces.Treatment))
	})
	return _c
}

func (_c *TrafficAllocatorInterface_GetTreatmentCode_Call) Return(s string, err error) *TrafficAllocatorInterface_GetTreatmentCode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TrafficAllocatorInterface_GetTreatmentCode_Call) RunAndReturn(run func(thresholds []uint32, treatments []interfaces.Treatment) (string, error)) *TrafficAllocatorInterface_GetTreatmentCode_Call {
	_c.Call.Return(run)
	return _c
}

// Rand provides a mock function for the type TrafficAllocatorInterface
func (_mock *TrafficAllocatorInterface) Rand() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rand")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// TrafficAllocatorInterface_Rand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rand'
type TrafficAllocatorInterface_Rand_Call struct {
	*mock.Call
}

// Rand is a helper method to define mock.On call
func (_e *TrafficAllocatorInterface_Expecter) Rand() *TrafficAllocatorInterface_Rand_Call {
	return &TrafficAllocatorInterface_Rand_Call{Call: _e.mock.On("Rand")}
}

func (_c *TrafficAllocatorInterface_Rand_Call) Run(run func()) *TrafficAllocatorInterface_Rand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TrafficAllocatorInterface_Rand_Call) Return(v uint32) *TrafficAllocatorInterface_Rand_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *TrafficAllocatorInterface_Rand_Call) RunAndReturn(run func() uint32) *TrafficAllocatorInterface_Rand_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConfiguration provides a mock function for the type TrafficAllocatorInterface
func (_mock *TrafficAllocatorInterface) UpdateConfiguration(experimentConfiguration *interfaces.ExperimentConfiguration) error {
	ret := _mock.Called(experimentConfiguration)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfiguration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*interfaces.ExperimentConfiguration) error); ok {
		r0 = returnFunc(experimentConfiguration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TrafficAllocatorInterface_UpdateConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConfiguration'
type TrafficAllocatorInterface_UpdateConfiguration_Call struct {
	*mock.Call
}

// UpdateConfiguration is a helper method to define mock.On call
//   - experimentConfiguration
func (_e *TrafficAllocatorInterface_Expecter) UpdateConfiguration(experimentConfiguration interface{}) *TrafficAllocatorInterface_UpdateConfiguration_Call {
	return &TrafficAllocatorInterface_UpdateConfiguration_Call{Call: _e.mock.On("UpdateConfiguration", experimentConfiguration)}
}

func (_c *TrafficAllocatorInterface_UpdateConfiguration_Call) Run(run func(experimentConfiguration *interfaces.ExperimentConfiguration)) *TrafficAllocatorInterface_UpdateConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*interfaces.ExperimentConfiguration))
	})
	return _c
}

func (_c *TrafficAllocatorInterface_UpdateConfiguration_Call) Return(err error) *TrafficAllocatorInterface_UpdateConfiguration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TrafficAllocatorInterface_UpdateConfiguration_Call) RunAndReturn(run func(experimentConfiguration *interfaces.ExperimentConfiguration) error) *TrafficAllocatorInterface_UpdateConfiguration_Call {
	_c.Call.Return(run)
	return _c
}
